name: Sara Beth Fachetti
favicon: null
layout_spectrum: 0.7437
typography_spectrum: 0.98571
title: Sara Beth Fachetti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01010d'
    - '#928575'
    - '#fb4193'
    - '#c5bfb4'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.9351475501898676
purpose: []
